### PR TITLE
Add vanilla section and improve contribute

### PR DESCRIPTION
**Pull request by edlerd**
* rename web section to vanilla
* add content from vanilla home page
* adjust design home vanilla section with content
* extend contributions page content and adjust layout

### CODE REVIEW

**Review by ClementChaumel — APPROVED** [review]
LGTM code wise

**Review by pedoch — COMMENTED** [review]
Everything looks good. My only note is that I think it'll be good to use the `image-template` for images. I know @bartaz mentioned this once. But maybe is something we can do later.

**Comment by edlerd** [comment]
> The demo is not running so I can't QA right now but it looks good!

Triggered the start demo manually and now the demo is there.

**Comment by bartaz** [comment]
Some conflict to resolve after new layout was merged.

Good call on the image tag @pedoch, would be nice to have that.
I guess some sections of the Vanilla page can be dropped (our home page is not great), but lets merge it and clean it up later.

**Review by pedoch — APPROVED** [review]

**Comment by edlerd** [comment]
All the things should be fixed. using the image template now.

**Pull request merged**
