### PR TITLE
Design site refresh

### PR DESCRIPTION
**Pull request by bartaz**
## Done

A quick refresh of design site pages to remove legacy layout and components and use more of the new surus and layouts.

## QA

Review pages, make sure they look ok.

- [home](https://design-ubuntu-com-310.demos.haus/)
- [brand](https://design-ubuntu-com-310.demos.haus/brand)
- [font](https://design-ubuntu-com-310.demos.haus/font)
- [vanilla](https://design-ubuntu-com-310.demos.haus/vanilla)
- [accessibility](https://design-ubuntu-com-310.demos.haus/accessibility)
- [resources](https://design-ubuntu-com-310.demos.haus/resources)
- [contribute](https://design-ubuntu-com-310.demos.haus/contribute)

image

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
- images should have .5rem margin-top (we use .p-image-wrapper on u.c and c.c for that), and hrs should have p-rule:
image

- don't see the email signature I had added at the bottom of the resources page

**Comment by bartaz** [comment]
> * don't see the email signature I had added at the bottom of the resources page

Email signature is not in scope of this PR. I want to do design updates first.

**Comment by lyubomir-popov** [comment]
Can we do something like this on the Brand page:
image


Font and vanilla will need some further work, but can be left as is for now.

**Review by chillkang — APPROVED** [review]
LGTM👍 Ubuntu font tester is super cool

**Pull request merged**
