### PR TITLE
update vf, add email signature template

### PR DESCRIPTION
**Pull request by lyubomir-popov**
## Done

Add email signature to the resources page, update vanilla to 4.9
N.B.: still waiting for actual signautre markup, do not merge before that's been updated.

## QA

[List of steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@bartaz external css seems to add lines and alter the look of this. I tried an iframe, but it becomes invisible. Can you please have a look?

**Comment by bartaz** [comment]
@lyubomir-popov This PR just changes too much (Vanilla update, footer/layout changes that are broken, email template itself that is unclear what it's meant to be doing and how it should look like).

I'm gonna close this and separate some of the updates to separate PRs.
As for the email template - best open an issue with what we want to build. Embedding email HTML inside the page template will not work.

**Comment by bartaz** [comment]
Reopening to keep demo running.

**Comment by bartaz** [comment]
This is now covered in #310 and #311

**Pull request closed without merging**
