### PR TITLE
Invoke cookie policy before gtm

### PR DESCRIPTION
**Pull request by britneywwc**
## Done

- Move cookie policy before GTM

## QA

- Go to demo
- Open dev tools and go to Networks tab
- Check that the cookie policy finishes its updates before GTM script invoked

## Issue / Card

Fixes [WD-15451](https://warthogs.atlassian.net/browse/WD-15451) and [WD-15825](https://warthogs.atlassian.net/browse/WD-15825)

## Screenshots

[if relevant, include a screenshot]

[WD-15451]: https://warthogs.atlassian.net/browse/WD-15451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-15825]: https://warthogs.atlassian.net/browse/WD-15825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by laszlokajtar** [comment]
@britneywwc i don't see any consent-related information here. is the version of the cookie policy the same as in charmed-kubeflow?

**Comment by britneywwc** [comment]
@laszlokajtar Yes they are both using the same cookie-policy versions 3.6.4. Can you attach a screenshot of what's missing here?

**Comment by laszlokajtar** [comment]
@britneywwc i'm missing the consent values from the dataLayer array objects created by this:
https://github.com/canonical/cookie-policy/blob/ff74c6309df9a2cee4f8c9ef4862c4e991635262/src/js/utils.js#L104

dataLayer on design:
image

dataLayer on charmed kubeflow with the consent values:
image

**Comment by britneywwc** [comment]
Thanks for linking the source of issue, that is out of scope for this task so I'll create a separate ticket for the cookie-policy fix.

**Comment by laszlokajtar** [comment]
consent info is not present in the dataLayer
image

**Review by laszlokajtar — APPROVED** [review]
lgtm!
image

**Review by immortalcodes — APPROVED** [review]

**Pull request merged**
